core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sessions.models import Session
from timetable.admin import events_site
from custom_admins.lessonsadmin import lessons_admin_site
from custom_admins.usersadmin import users_admin_site
from custom_admins.swimsadmin import swims_admin_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('events/', events_site.urls),
    # Allauth
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='user')),
    # Lessons
    path('lessons/',
         include('lessons.urls', namespace='lessons')),
    path('lessons_orders/',
         include('lessons_orders.urls', namespace='lessons_orders')),
    path('', include('lessons_bookings.urls', namespace='lessons_bookings')),
    # Swims
    path('swims/', include('swims.urls', namespace='swims')),
    path('swims_orders/',
         include('swims_orders.urls', namespace='swims_orders')),
    # Schools
    path('schools/', include('schools.urls', namespace='schools')),
    path('schools_orders/',
         include('schools_orders.urls', namespace='schools_orders')),
    path('', include('schools_bookings.urls', namespace='schools_bookings')),

   # Shopping
    path('shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),

    # Others
    path('timetable/', include('timetable.urls')),
    path('hijack/', include('hijack.urls')),
    path('reports/', include('reports.urls')),
    # BOIPA
    path('boipa/', include(('boipa.urls', 'boipa'), namespace='boipa')),  # Note the namespace argument
    # Waiting List
    path('waiting-list/', include('waiting_list.urls')),
]
# Serve static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

# Add Admin Sites
urlpatterns += [path('lessonsadmin/', lessons_admin_site.urls),
                path('usersadmin/', users_admin_site.urls),
                path('swimsadmin/', swims_admin_site.urls)
                ]
# add auto reload
urlpatterns += [path('__reload__/', include('django_browser_reload.urls'))]


# Change Site Labels
admin.site.site_header = "TCSP Administration"
admin.site.site_title = "TCSP Administration site"
admin.site.index_title = "TCSP Administration"

schools/urls.py
from django.urls import path
from . import views

app_name = 'schools'

urlpatterns = [
    path('school_list/', views.school_list, name='school_list'),
    path('add-new-swimling/', views.add_new_swimling, name='add_new_swimling'),
    path('load-new-swimling-form/<slug:product_slug>/', views.load_new_swimling_form, name='load_new_swimling_form'),
    path('school_detail/<int:pk>/', views.school_detail, name='school_detail'),
    # Place specific URLs before the more general category_slug pattern
    path('success/', views.swimling_success, name='swimling_success'),
    path('failure/', views.swimling_failure, name='swimling_failure'),
    path('<slug:category_slug>/', views.school_list, name='schools_list_by_category'),
    path('<int:id>/<slug:slug>/', views.school_detail, name='schools_detail_again'),  # Ensure unique name if needed
]

schools/models.py
from django.db import models
from django.urls import reverse
from datetime import time
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from enum import Enum


# School Information
class ScoSchool(models.Model):
    name = models.CharField(max_length=50, default='', blank=True)
    sco_role_num = models.CharField(max_length=7, default='',  unique=True, blank=True)
    add1 = models.CharField(max_length=50, default='', blank=True)
    add2 = models.CharField(max_length=50, default='', blank=True)
    add3 = models.CharField(max_length=50, default='', blank=True)
    eircode = models.CharField(max_length=7, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    email = models.EmailField(max_length=50, default='', blank=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class ScoProgram(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


# A list of categores of lessons
class ScoCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True, blank=True)
    program = models.ForeignKey(ScoProgram, on_delete=models.CASCADE, related_name="sco_categories")

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'School category'
        verbose_name_plural = 'School categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('schools:schools_list_by_category',
                       args=[self.slug])


class Weekday(Enum):
    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6

    @classmethod
    def choices(cls):
        return [(key.value, key.name.title()) for key in cls]


#     Lessons
class ScoLessons(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(ScoCategory, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, blank=True)
    start_time = models.TimeField(blank=True, default=time(hour=8, minute=0))
    end_time = models.TimeField(blank=True, default=time(hour=9, minute=0))
    day_of_week = models.PositiveSmallIntegerField(choices=Weekday.choices())
    num_places = models.IntegerField(null=True)
    num_weeks = models.IntegerField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, )
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              default='images/default_image.jpg')
    school = models.ForeignKey(
        ScoSchool,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='school_lessons'  # Optional: sets a name for the reverse relation from ScoSchool to ScoTerm
    )

    def save(self, *args, **kwargs):
        # Create the name by combining other fields
        self.name = self.generate_name()
        super().save(*args, **kwargs)

    def generate_name(self):
        day_name = Weekday(self.day_of_week).name  # Access the name attribute of the enum
        start_time_str = self.start_time.strftime('%H:%M')
        end_time_str = self.end_time.strftime('%H:%M')
        return f"{self.category} - {day_name} - {start_time_str} to {end_time_str}"

    class Meta:
        verbose_name = 'School Lessons'
        verbose_name_plural = "School Lessons"
        ordering = ['day_of_week']

    def get_absolute_url(self):
        return reverse('schools:detail',
                       args=[self.id, self.slug])

    def __str__(self):
        start_time_formatted = self.start_time.strftime("%H:%M %p")
        day_of_week = Weekday(self.day_of_week).name  # Use Enum to get the day name
        return f"{self.category} - {day_of_week} - {start_time_formatted}"

    def get_num_sold(self):
        from schools_bookings.models import ScoEnrollment
        return ScoEnrollment.objects.filter(lesson=self).count()  # Count the number of related orders

    def get_num_left(self):
        return self.num_places - self.get_num_sold()

    # new method
    def remaining_spaces(self):
        enrollments_count = self.scoenrollment_set.count()
        return max(self.num_places - enrollments_count, 0)

    @property
    def is_full(self):
        return self.remaining_spaces() == 0


# update name everytime fields are changed
@receiver(pre_save, sender=ScoLessons)
def update_product_name(sender, instance, **kwargs):
    instance.name = instance.generate_name()
    instance.slug = slugify(instance.name)


# Create Slug
@receiver(pre_save, sender=ScoCategory)
def update_category_slug(sender, instance, **kwargs):
    if not instance.slug:  # Generate slug only if it doesn't already exist
        instance.slug = slugify(instance.name)

        # Ensure slug uniqueness (basic example)
        original_slug = instance.slug
        queryset = ScoCategory.objects.filter(slug__iexact=instance.slug)
        if instance.pk:  # Exclude current instance in case of update
            queryset = queryset.exclude(pk=instance.pk)
        count = 1
        while queryset.exists():
            instance.slug = f"{original_slug}-{count}"
            count += 1
            queryset = ScoCategory.objects.filter(slug__iexact=instance.slug)
            if instance.pk:
                queryset = queryset.exclude(pk=instance.pk)

users/forms.py
from django import forms
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from .models import UserProfile, Swimling

# Get the custom user model
User = get_user_model()


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=150, required=True)
    lessons = forms.BooleanField(label="I wish to apply for children's lessons",
                                 required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['password1'].help_text = (
            "Must be 8+ characters, not too common or all numbers."
        )

    def save(self, request):
        # Call the parent save method to create the user instance
        user = super().save(request)

        # Check if the 'lessons' checkbox is checked
        if self.cleaned_data.get('lessons', False):
            # Replace 'Guardian' with the name of the group you want to assign the user to
            group_name = 'Guardian'
            group, _ = Group.objects.get_or_create(name=group_name)
            user.groups.add(group)

        # Return the user instance
        return user


# Update Profile - NOW WITH USERNAME
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add help text and styling
        self.fields['username'].help_text = (
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        )
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Enter your username'
        })
        self.fields['first_name'].widget.attrs.update({
            'placeholder': 'Enter your first name'
        })
        self.fields['last_name'].widget.attrs.update({
            'placeholder': 'Enter your last name'
        })

    def clean_username(self):
        """Ensure username is unique (excluding current user)"""
        username = self.cleaned_data['username']

        # Get the current user instance
        user_id = self.instance.pk if self.instance else None

        # Check if username exists for other users
        if User.objects.filter(username=username).exclude(pk=user_id).exists():
            raise forms.ValidationError("A user with that username already exists.")

        return username


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('notes',)
        widgets = {
            'notes': forms.Textarea(attrs={
                'rows': 4,
                'placeholder': 'Add any personal notes or preferences...'
            }),
        }


class NewSwimlingForm(forms.ModelForm):
    class Meta:
        model = Swimling
        fields = ['first_name', 'last_name', 'dob', 'sco_role_num', 'notes']
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),
            'notes': forms.Textarea(attrs={'rows': 4}),
        }
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'dob': 'Date of Birth',
            'sco_role_num': 'School Role Number',
            'notes': 'Additional Notes'
        }

schools/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse
from users.forms import NewSwimlingForm
from shopping_cart.forms import CartAddProductForm
from .models import ScoProgram, ScoCategory, ScoLessons, ScoSchool
from users.models import Swimling
import django_filters
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from .filters import LessonFilter


# Get Lesson list for public lessons  Active=1
def school_list(request):
    sco_filter = LessonFilter(request.GET, queryset=ScoLessons.objects.all())

    if request.headers.get('HX-Request'):  # Check for HTMX request
        # Return only the part of the page that contains the filtered results
        return render(request, 'schools/partials/_lesson_list.html', {
            'lessons': sco_filter.qs
        })

    # Return the full page for non-AJAX requests
    return render(request, 'schools/products/sco_lessons.html', {
        'form': sco_filter.form,
        'lessons': sco_filter.qs
    })


@login_required
def school_detail(request, pk):
    product = get_object_or_404(ScoLessons, pk=pk)
    form = NewSwimlingForm()
    cart_product_form = CartAddProductForm(user=request.user)  # Instantiate the form
    swimlings = Swimling.objects.filter(guardian=request.user)  # Assuming association via guardian

    return render(request, 'schools/products/detail.html', {
        'product': product,
        'cart_product_form': cart_product_form,
        'form': form,
        'swimlings': swimlings,  # Pass swimlings to the template
    })


def product_list(request):
    filter = ProductFilter(request.GET, queryset=Product.objects.all())

    # Check if a "clear_filters" parameter is present in the request
    if 'clear_filters' in request.GET:
        filter = ProductFilter(queryset=Product.objects.all())  # Create a fresh filter without any filters applied

    return render(request, 'schools/products/list_filter.html', {'filter': filter})


def add_new_swimling(request):
    if request.method == 'POST':
        form = NewSwimlingForm(request.POST)
        if form.is_valid():
            new_swimling = form.save(commit=False)
            new_swimling.guardian = request.user
            new_swimling.save()

            # Fetch updated swimlings for the dropdown
            swimlings = Swimling.objects.filter(guardian=request.user)
            # success message
            messages.success(request, 'Swimling added successfully.')
            # Render the partial template for the dropdown
            rendered_html = render_to_string('partials/swimlings_list.html', {'swimlings': swimlings},
                                             request=request)

            # Respond with the rendered HTML for HTMX to swap
            return HttpResponse(rendered_html)
        else:
            if "HX-Request" in request.headers:
                # If form is invalid during an HTMX request, return the form with errors
                context = {'form': form}
                html = render_to_string('partials/new_swimling_form.html', context, request=request)
                return HttpResponse(html, status=400)
            else:
                # For non-HTMX, render the form with errors within the context of a full page
                return render(request, 'partials/new_swimling_form.html', {'form': form})

    else:
        form = NewSwimlingForm()
        return render(request, 'partials/new_swimling_form.html', {'form': form})


# Success view
def swimling_success(request):
    return render(request, 'schools/success.html')


# Failure view
def swimling_failure(request):
    return render(request, 'schools/failure.html')


def load_new_swimling_form(request, product_slug):
    form = NewSwimlingForm()
    product = ScoLessons.get(slug=product_slug)  # Retrieve the product based on the slug
    return render(request, 'partials/new_swimling_form.html', {'form': form, 'product': product})

schools/templates/schools/partials/_lesson_list.html
{% if lessons %}
<div class="container mx-auto px-4 sm:px-6 lg:px-8 mt-5">
    <div class="flex justify-center">
        <div class="w-full lg:w-11/12 bg-white shadow-md rounded my-6">
            <table class="min-w-full leading-normal">
                <thead>
                    <tr>
                        <th scope="col" class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-800 uppercase tracking-wider">
                            Name
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-800 uppercase tracking-wider">
                            Price
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-800 uppercase tracking-wider">
                            School
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-800 uppercase tracking-wider">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    {% for lesson in lessons %}
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            {{ lesson.generate_name }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                           € {{ lesson.price | floatformat:2 }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            {{ lesson.school }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <a href="{% url 'schools:school_detail' lesson.pk %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                Book Now
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% else %}
    <div class="container mx-auto px-4 sm:px-6 lg:px-8 mt-5">
        <div class="flex justify-center">
            <div class="w-full lg:w-11/12 bg-white shadow-md rounded my-6 p-6">
                <p class="text-gray-900 text-sm">No lessons found.</p>
            </div>
        </div>
    </div>
{% endif %}

schools/templates/schools/partials/new_swimling_form.html
<div x-data="{ showModal: false }">
    <!-- Button to open the modal -->
    <button @click="showModal = true" class="bg-blue-500 text-white font-bold py-2 px-4 rounded">
        Add new Swimmer
    </button>

    <!-- Modal Structure -->
    <div class="fixed z-10 inset-0 overflow-y-auto" style="display: none;" x-show="showModal" x-cloak>
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <!-- Background overlay, show/hide based on modal state. -->
            <div class="fixed inset-0 transition-opacity" aria-hidden="true" @click="showModal = false">
                <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <!-- Modal panel, show/hide based on modal state. -->
            <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6"
                 role="dialog" aria-modal="true" aria-labelledby="modal-headline">
                <div>
                    <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                        <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-headline">
                            Add New Swimling
                        </h3>
                        <form action="{% url 'lessons:add_new_swimling' %}" method="POST"
                              hx-post="{% url 'lessons:add_new_swimling' %}"
                              hx-target="#swimling_dropdown"
                              hx-swap="outerHTML"
                              hx-after-swap="showModal = false"  <!-- Directly change Alpine.js state -->
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight
                        focus:outline-none focus:shadow-outline">
                        {% csrf_token %}
                        <!-- First Name -->
                        <div class="mb-4">
                            <label for="id_first_name" class="block text-gray-700 text-sm font-bold mb-2">
                                First Name
                            </label>
                            <input type="text" name="first_name" id="id_first_name"
                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                   placeholder="John">
                        </div>

                        <!-- Last Name -->
                        <div class="mb-4">
                            <label for="id_last_name" class="block text-gray-700 text-sm font-bold mb-2">
                                Last Name
                            </label>
                            <input type="text" name="last_name" id="id_last_name"
                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                   placeholder="Doe">
                        </div>

                        <!-- Date of Birth -->
                        <div class="mb-4">
                            <label for="id_dob" class="block text-gray-700 text-sm font-bold mb-2">
                                Date of Birth
                            </label>
                            <input type="date" name="dob" id="id_dob"
                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                        </div>

                        <!-- School Role Number -->
                        <div class="mb-4">
                            <label for="id_sco_role_num" class="block text-gray-700 text-sm font-bold mb-2">
                                School Role Number
                            </label>
                            <input type="text" name="sco_role_num" id="id_sco_role_num"
                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                   placeholder="12345">
                        </div>

                        <!-- Additional Notes -->
                        <div class="mb-4">
                            <label for="id_notes" class="block text-gray-700 text-sm font-bold mb-2">
                                Additional Notes
                            </label>
                            <textarea name="notes" id="id_notes"
                                      class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                      rows="4"
                                      placeholder="Enter additional notes here..."></textarea>
                        </div>
                        <div>
                            <input @click="setTimeout(() => showModal = false, 500)" type="submit"
                                   class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                                   value="Submit"></div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Modal footer actions -->
            <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                <button type="button"
                        class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
                        @click="showModal = false">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>
</div>

schools/templates/schools/partials/schools_list.html
{% load static %}

{% block content %}
    <div class="bg-blue-500 p-3">
        <h1 class="text-2xl text-white text-center">School Swim Lessons</h1>
    </div>
    <div class="container mx-auto mt-6">
        <div class="row">
            <div class="col-md-11">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Lessons</th>
                         <th>School</th>
                        <th>Spaces</th>
                        <th>Places</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for lesson in page_obj %}
                        <tr>
                            <td>{{ lesson.name }}</td>
                             <td>{{ lesson.school.sco_name }}</td>
                            <td>{{ lesson.num_places }}</td>
                            <td>
                                {% if lesson.remaining_spaces <= 0 %}
                                    <p>Full</p>
                                {% else %}
                                    <p>{{ lesson.remaining_spaces }}</p>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'schools:school_detail' slug=lesson.slug %}" class="btn btn-info
                          btn-sm">Book</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Pagination Navigation with Tailwind -->
   <nav aria-label="Page navigation" class="flex justify-center mt-4">
    <ul class="inline-flex -space-x-px">
        <!-- First and Previous Page Links -->
        <li>
            <a href="?page=1" class="py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700" aria-label="Go to first page">
                ««
            </a>
        </li>
        {% if page_obj.has_previous %}
        <li>
            <a href="?page={{ page_obj.previous_page_number }}" class="py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700" aria-label="Go to previous page">
                «
            </a>
        </li>
        {% endif %}

        <!-- Numbered Page Links -->
        {% for num in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ num }}" class="{% if page_obj.number == num %}py-2 px-3 leading-tight text-gray-500 bg-blue-500 text-white border border-blue-500 hover:bg-blue-600 hover:text-white{% else %}py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700{% endif %}">
                {{ num }}
            </a>
        </li>
        {% endfor %}

        <!-- Next and Last Page Links -->
        {% if page_obj.has_next %}
        <li>
            <a href="?page={{ page_obj.next_page_number }}" class="py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700" aria-label="Go to next page">
                »
            </a>
        </li>
        <li>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700" aria-label="Go to last page">
                »»
            </a>
        </li>
        {% endif %}
    </ul>
</nav>



{% endblock %}

schools/templates/schools/partials/swimlings_list.html
{% if messages %}
    {% for message in messages %}
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                {{ message }}
            </div>
    {% endfor %}
{% endif %}

<div id="swimling_dropdown" class="form-group w-1/3 pb-3">
    <label for="id_swimling">Select Swimling</label>
    <select name="swimling" id="id_swimling"
            class="form-control block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md text-black">
        {% for swimling in swimlings %}
            <option value="{{ swimling.id }}" class="text-black">{{ swimling }}</option>
        {% endfor %}
    </select>
</div>